export enum UserRole {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  PRODUCT_MARKETING_STAFF = 'PRODUCT_MARKETING_STAFF',
  SALES_OPERATIONS_STAFF = 'SALES_OPERATIONS_STAFF',
  CSR = 'CSR',
  CUSTOMER = 'CUSTOMER',
}
